### ISSUE TITLE
pwalk silently skips data

### ISSUE THREAD

**Issue by dirkpetersen** [fizwit/filesystem-reporting-tools#1]
I do have access to _ADM, but pwalk only returns a little bit

petersen@rhino3:/home…rk/slurm-pwalk$ cat csv_petersen/_ADM.csv 
5253122241,4422936610,1,"/fh/fast/_ADM/SciComp/data.csv","csv",35410,158372,232295443,607188,"0100660",1480615347,1480615406,1480615406,-1,0
4695702076,4422936610,1,"/fh/fast/_ADM/SciComp/.DS_Store","",31554,158372,6148,51,"0102775",1479245482,1479245488,1479245488,-1,0

petersen@rhino3:/home…rk/slurm-pwalk$ ls -la /fh/fast/_ADM
total 287
drwxrwsr-x   8 root         1011752 147 Sep 30 05:39 .
drwxr-xr-x 281 root root              0 Dec  8 10:59 ..
drwxrws--x   3 root _ADM_ExtAff_grp  54 May 29  2015 ExtAff
drwxrwsr-x   7 root root            124 May 17  2016 IT
drwxrwsr-x  22 root SciComp         733 Dec  1 11:05 SciComp

**Comment by dirkpetersen** [comment]
if I run as me it creates only very few entries 

petersen@rhino3:$ pwalker --NoSnap  --maxthreads=16 /fh/fast/_ADM/SciComp | wc -l
29

but if I run as root it seems to find everything

**Comment by fizwit** [comment]
setuid too root has been added to pwalk.   
Recomended usage is to set owner to root and group to a local sysadmin group.  Change file mode to setuid with zero file permissions to other. 
chown root:sysadmin_g pwalk
chmod 4770 pwalk
ls -l pwalk
-rwsrwx--- 1 root sysadmin 14376 Dec  9 13:19 pwalk
