### ISSUE TITLE
add a header switch

### ISSUE THREAD

**Issue by bmcgough** [fizwit/filesystem-reporting-tools#16]
Many tools for CSV analysis can construct a schema when a header row is present at the beginning of the output.

A command line switch to print a single line at the beginning of pwalk output naming the fields would be useful. Of course, some would not want that, do the default should be to not print.

I would suggest sticking to the stat struct names for stat struct data (ex: st_size, st_mtime) to avoid possible confusion.

**Comment by fizwit** [comment]
--header flag is implemented
