### ISSUE TITLE
no white space in file names supported ?

### ISSUE THREAD

**Issue by dirkpetersen** [fizwit/filesystem-reporting-tools#2]
you can check 

grep "Bad File" -R slurrm_pwalk/output_petersen/* | wc -l
4849

other characters are may be affected as well

**Comment by fizwit** [comment]
pwalk removes control characters from file names.  ASCII values less than 32, these are also know as the C0 Unicode control codes.  Spaces are allowed in file names. File names that contain control characters are written to the "bad file" log but they are also included in the CSV output files (sans control characters). Double quote character is escaped for CSV compliant output. File names are byte streams with ASCII codes between 32 and 255. Cleaning the C0 characters from files names was necessary to import data into MYSQL.
