### ISSUE TITLE
lots of errors in BeeGFS

### ISSUE THREAD

**Issue by dirkpetersen** [fizwit/filesystem-reporting-tools#3]
when I scan files in out beegfs system I get predominantly bad files 

sudo /app/bin/pwalker --NoSnap  --maxthreads=16 /fh/scratch/delete30

**Comment by bmcgough** [comment]
fhgfs version 2014.01.0r12.debian7 is what is in use here. We should be able to test against an updated version of BeeGFS very soon to see if we continue to get bad files.

**Comment by fizwit** [comment]
The main issue with BeeGFS is the very large inode numbers.  This is fixed with 64bit output of inodes.
