### ISSUE TITLE
Implement double quote escape

### ISSUE THREAD

**Issue by bmcgough** [fizwit/filesystem-reporting-tools#7]
https://tools.ietf.org/html/rfc4180

IETF defines double quote escapes in CSV as an additional double quote, not backslash.

Can you implement an option to use double quote as an escape character instead of backslash?

**Comment by fizwit** [comment]
Making your issue the new default behavior. The only character that is quoted in a string is the double quote which is quoted with a double quote. Control characters are discarded.
