### ISSUE TITLE
Implement -NoSnap as an exclude where I can provide a list of things to exclude

### ISSUE THREAD

**Issue by bmcgough** [fizwit/filesystem-reporting-tools#8]
Ex:

pwalk -exclude="/store/it/email/spool","/store/business/folder dump","/store/loser/way too many ""files"" here"

Not sure how best to manage quoted strings in a list - going with CSV style.

**Comment by fizwit** [comment]
implemented as --exclude exclude_file
<exclude_file> is the name of a file contains directories to be excluded. The excluded directory names need to be listed one per line.  The format of the filenames should match the style of the filenames as reported by pwalk (relative or absolute).  Pwalk "verifies" the list of files by performing an lstat on each file. If a file is not found an error is written to stderr and processing continues.
